# Dependencies
markdown:	kramdown
# Permalinks
permalink:	/blog/:title

# Setup
title:            Patrick M端nch Blog
tagline:          'blog'
description:      'Patrick M端nch Blog'
url:              http://atomic111.github.io
baseurl:
commentsystem:    google
disqus:           example

author:
  name:           Patrick M端nch
  url:            https://twitter.com/atomiczero111

paginate:         5

# Custom vars
icon:             /assets/images/logo.jpeg
cover:            /assets/images/cover.jpeg

social:
  - icon:         twitter
    url:          https://twitter.com/atomiczero111
    desc:         Follow us on twitter

  - icon:         github
    url:          https://github.com/atomic111
    desc:         Fork us on github

menu:
  - title:        Home
    url:          /

copyright:
  author:         Patrick M端nch
  url:            http://atomic111.github.io/
  type_title:     All rights reserved

parallax:         true

# Google Analytics (add the UA Code, e.g.: UA-xxxxxxxx-1)
google_analytics: UA-74418092-1

# Default Theme Color for Chrome on Android Lollipop (Use RGB ColorCode without `#`, e.g.: `db5945`)
theme_color:       7E9576
